// ============================================================
// DATABASE SISWA - SMP N 5 KLATEN
// Kelas IX A - IX H | 256 Siswa
// ============================================================

const SCHOOL_NAME = "SMP Negeri 5 Klaten";
const EVENT_NAME = "Pelepasan Siswa Kelas IX";
const SCHOOL_YEAR = "Tahun Pelajaran 2025/2026";
const QR_PREFIX = "SMPN5KLT2026";

// Raw student data: [overallNo, name, class, classNo, gender]
const RAW_STUDENTS = [
  // === IX A ===
  [1, "Aji Mandala", "IX A", 1, "M"],
  [2, "Aliefa Nailla Nur Azhira", "IX A", 2, "F"],
  [3, "Alif Adi Saputra", "IX A", 3, "M"],
  [4, "Alvin Rey Putranto", "IX A", 4, "M"],
  [5, "Anisa Safa Hafizah", "IX A", 5, "F"],
  [6, "Ardila Ayu Pratiwi", "IX A", 6, "F"],
  [7, "Arga Wisnu Kuncoro", "IX A", 7, "M"],
  [8, "Ashila Nindya Putri", "IX A", 8, "F"],
  [9, "Berlian Elsafira", "IX A", 9, "F"],
  [10, "Billal Raffa Pratama", "IX A", 10, "M"],
  [11, "Chelsea Olyvia", "IX A", 11, "F"],
  [12, "Dinova Aulia Devi", "IX A", 12, "F"],
  [13, "Farhan Prasetyo", "IX A", 13, "M"],
  [14, "Hasna Rafania", "IX A", 14, "F"],
  [15, "Lael Argatha Prasetia", "IX A", 15, "M"],
  [16, "Luthfi Furdianto", "IX A", 16, "M"],
  [17, "Muhammad Hafidzun Alim", "IX A", 17, "M"],
  [18, "Nadia Firdha Ramadhani", "IX A", 18, "F"],
  [19, "Naifah Dini Aulia Konita", "IX A", 19, "F"],
  [20, "Noval Akbar Wibisono", "IX A", 20, "M"],
  [21, "Nurul Isti Rahmawati", "IX A", 21, "F"],
  [22, "Oktaviana Syaputri", "IX A", 22, "F"],
  [23, "Olivia Clariza Putri", "IX A", 23, "F"],
  [24, "Raditia Firmansah", "IX A", 24, "M"],
  [25, "Raditya Hanung Pratama", "IX A", 25, "M"],
  [26, "Revandy Vicki Al Hidayat", "IX A", 26, "M"],
  [27, "Risa Cahyaningrum", "IX A", 27, "F"],
  [28, "Sandy Arsena Lianto", "IX A", 28, "M"],
  [29, "Satria Putra Pratama", "IX A", 29, "M"],
  [30, "Umi Kulsum", "IX A", 30, "F"],
  [31, "Zahro Nuuri Fadila", "IX A", 31, "F"],
  [32, "Ziilal Rizky Putra Purnomo", "IX A", 32, "M"],
  // === IX B ===
  [33, "Agatha Novita Sari", "IX B", 1, "F"],
  [34, "Akhdan Latif Azizan", "IX B", 2, "M"],
  [35, "Aliya Shaista Nafisa Risqi", "IX B", 3, "F"],
  [36, "Amelia Rahma", "IX B", 4, "F"],
  [37, "Amelinda Eka Ramadhani", "IX B", 5, "F"],
  [38, "Arifah Nuraini Tri Utami", "IX B", 6, "F"],
  [39, "Arina Qurrota A'ina", "IX B", 7, "F"],
  [40, "Arsya Putra Pratama", "IX B", 8, "M"],
  [41, "Asyifa Azizi Rohmah", "IX B", 9, "F"],
  [42, "Aulia Syifa Zavira", "IX B", 10, "F"],
  [43, "Aurel Putri Ramadhani", "IX B", 11, "F"],
  [44, "Avian Fajar Prasetya", "IX B", 12, "M"],
  [45, "Bimo Seto", "IX B", 13, "M"],
  [46, "Briliant Ardie Pratama", "IX B", 14, "M"],
  [47, "Fahrel Bima Putra", "IX B", 15, "M"],
  [48, "Fahreza Azka Hendrayudha", "IX B", 16, "M"],
  [49, "Husna Haura Muslimah", "IX B", 17, "M"],
  [50, "Lathifa Syahla", "IX B", 18, "F"],
  [51, "Lukman Nur Afandi", "IX B", 19, "M"],
  [52, "Maria Fiorenza Leony Putri Listiartanto", "IX B", 20, "F"],
  [53, "Muhammad Ardi Sutoro", "IX B", 21, "M"],
  [54, "Nathan Raditya Nur Athaillah", "IX B", 22, "M"],
  [55, "Nuha Nufaisah", "IX B", 23, "F"],
  [56, "Pandu Ari Pratama", "IX B", 24, "M"],
  [57, "Razel Zaki Al Ayyubi", "IX B", 25, "M"],
  [58, "Rizal Yasyfa Musthofa", "IX B", 26, "M"],
  [59, "Rudi Mahendra", "IX B", 27, "M"],
  [60, "Santi Wulandari", "IX B", 28, "F"],
  [61, "Septiana Rahmadani", "IX B", 29, "F"],
  [62, "Silvia Zahra Taryananda", "IX B", 30, "F"],
  [63, "Suci Ayu Fatimah", "IX B", 31, "F"],
  [64, "Zlathan Ibrahimovic Alxavi", "IX B", 32, "M"],
  // === IX C ===
  [65, "Albert Marcelo", "IX C", 1, "M"],
  [66, "Alviano Raditya Zelfa", "IX C", 2, "M"],
  [67, "Andrean Kelfin Nur Hidayat", "IX C", 3, "M"],
  [68, "Atika Rahma Ramadani", "IX C", 4, "F"],
  [69, "Ayunda Pertiwi", "IX C", 5, "F"],
  [70, "Bunga Pramesti", "IX C", 6, "F"],
  [71, "Catur Adi Pamungkas", "IX C", 7, "M"],
  [72, "Dhesya Avyf Fiestiana", "IX C", 8, "F"],
  [73, "Dinna Rahayu Puteri", "IX C", 9, "F"],
  [74, "Divia Zulfa Nareswari", "IX C", 10, "F"],
  [75, "Erhan Abdan Syukura", "IX C", 11, "M"],
  [76, "Ezalia Putri Purwaningsih", "IX C", 12, "F"],
  [77, "Fathan Hadi Gumilang", "IX C", 13, "M"],
  [78, "Gani Pangestu Aji", "IX C", 14, "M"],
  [79, "Hadyan Naufal Subastian", "IX C", 15, "M"],
  [80, "Khanza Shaulika Kurniawan", "IX C", 16, "F"],
  [81, "Mirza Dwi Aryanto", "IX C", 17, "M"],
  [82, "Mohammad Rafi Ramadhan", "IX C", 18, "M"],
  [83, "Nabila Lois Nathaniela", "IX C", 19, "F"],
  [84, "Nathaniel Putera Denhas Sridoyo", "IX C", 20, "M"],
  [85, "Nayla Agracia Octavirly", "IX C", 21, "F"],
  [86, "Rafkanaya Sarjani", "IX C", 22, "F"],
  [87, "Regina Silvi Nur Saudah", "IX C", 23, "F"],
  [88, "Rezika Duta Maherani", "IX C", 24, "F"],
  [89, "Rizik Saputra Dewa", "IX C", 25, "M"],
  [90, "Satrio Laghfa Galuh", "IX C", 26, "M"],
  [91, "Sherly Intan Fahdiana", "IX C", 27, "F"],
  [92, "Tifanny Renata Putri", "IX C", 28, "F"],
  [93, "Vino Ady Pratama", "IX C", 29, "M"],
  [94, "Wahid Wahyu Putra", "IX C", 30, "M"],
  [95, "Yunianto", "IX C", 31, "M"],
  [96, "Zifara Cahyaningrum", "IX C", 32, "F"],
  // === IX D ===
  [97, "Aditya Tegar Pamungkas", "IX D", 1, "M"],
  [98, "Alfarezy Saputra", "IX D", 2, "M"],
  [99, "Aryana Galih Pertiwi", "IX D", 3, "F"],
  [100, "Bayu Dwi Ardi Samudera", "IX D", 4, "M"],
  [101, "Dayana Abhi Takhbira", "IX D", 5, "F"],
  [102, "Dwi Nurlaila Putri", "IX D", 6, "F"],
  [103, "Fahira Syahrini Putri", "IX D", 7, "F"],
  [104, "Fanisya Cahya Ningrum", "IX D", 8, "F"],
  [105, "Ferdy Putra Yudiansyah", "IX D", 9, "M"],
  [106, "Gendhis Nur Fauziah Putri Arifah", "IX D", 10, "F"],
  [107, "Hafidz Hanif Al Wansyah", "IX D", 11, "M"],
  [108, "Ibnu Hanif Maulana", "IX D", 12, "M"],
  [109, "Ichsan Nurrohman", "IX D", 13, "M"],
  [110, "Iffa Ria Aditama", "IX D", 14, "F"],
  [111, "Isna Mida Ramadhani", "IX D", 15, "F"],
  [112, "Julyan Anugrah Pambudi Nugroho", "IX D", 16, "M"],
  [113, "Kesya Fazzura Rafaatur", "IX D", 17, "F"],
  [114, "Kheza Juwita Hari Mardiana", "IX D", 18, "F"],
  [115, "Muhamad Abiyyu Fadey Wibowo", "IX D", 19, "M"],
  [116, "Muhammad Dimas Saputra", "IX D", 20, "M"],
  [117, "Muhklis Bagus Riyadhi", "IX D", 21, "M"],
  [118, "Neisa Ardhani", "IX D", 22, "F"],
  [119, "Nurviana Eka Saputri", "IX D", 23, "F"],
  [120, "Raffy Hafidz Novianto", "IX D", 24, "M"],
  [121, "Reny Mustika Pramita", "IX D", 25, "F"],
  [122, "Ridaryatmo Aris Pramujo", "IX D", 26, "M"],
  [123, "Rizky Adha Saputra", "IX D", 27, "M"],
  [124, "Rossy Aditya Saputra", "IX D", 28, "M"],
  [125, "Sahrul Reno Ramadhan", "IX D", 29, "M"],
  [126, "Salsabila Azahra'", "IX D", 30, "F"],
  [127, "Sherin Achika Putri", "IX D", 31, "F"],
  [128, "Yessy Yuliyanti", "IX D", 32, "F"],
  // === IX E ===
  [129, "Adhi Nova Pratama", "IX E", 1, "M"],
  [130, "Adi Putra Dinata", "IX E", 2, "M"],
  [131, "Ananda Ulfiatul Maftuha", "IX E", 3, "F"],
  [132, "Arya Maulana", "IX E", 4, "M"],
  [133, "Aydan Hakim Chaeir", "IX E", 5, "M"],
  [134, "Azzam Aulia Ibrahim", "IX E", 6, "M"],
  [135, "Danang Widara Pandusuwargo", "IX E", 7, "M"],
  [136, "Danis Fitriana Putri", "IX E", 8, "F"],
  [137, "Diandra Eka Brillian", "IX E", 9, "F"],
  [138, "El Gabrielle Evan Fadhil Wardani", "IX E", 10, "M"],
  [139, "Erix Yusuf Fadillah", "IX E", 11, "M"],
  [140, "Fardhan Jamal", "IX E", 12, "M"],
  [141, "Fauzia Elvareta Artanti", "IX E", 13, "F"],
  [142, "Galvano Mohammad Rizky", "IX E", 14, "M"],
  [143, "Hanaa Najwa Attaqiyah", "IX E", 15, "F"],
  [144, "Hasib Firman Musthofa", "IX E", 16, "M"],
  [145, "Ismy Ayu Amadea Cyren", "IX E", 17, "F"],
  [146, "Jamaliya Nur'ainy", "IX E", 18, "F"],
  [147, "Kevin Dwi Kurniawan", "IX E", 19, "M"],
  [148, "Kurnia Eva Ariniati", "IX E", 20, "F"],
  [149, "Latifah Cantika Damayanti", "IX E", 21, "F"],
  [150, "Laura Kurnia Dewi", "IX E", 22, "F"],
  [151, "Mizan Puji Rizadli", "IX E", 23, "M"],
  [152, "Muhammad Imam Nur Sholeh", "IX E", 24, "M"],
  [153, "Nayla Khansa Putrika Ramadani", "IX E", 25, "F"],
  [154, "Prisilia Putri Santoso", "IX E", 26, "F"],
  [155, "Quinara Gazali Meka", "IX E", 27, "F"],
  [156, "Rehana Az-Zahra Syaputri", "IX E", 28, "F"],
  [157, "Rezky Auren Dewantara", "IX E", 29, "M"],
  [158, "Rochim Fajar Saputra", "IX E", 30, "M"],
  [159, "Syifa Agustina Ramadhani", "IX E", 31, "F"],
  [160, "Triska Cinta Maharani Syah Puteri", "IX E", 32, "F"],
  // === IX F ===
  [161, "Adib Mukhlisin", "IX F", 1, "M"],
  [162, "Adinda Kusumawati", "IX F", 2, "F"],
  [163, "Agastha Bima Muafaq Rifa'i", "IX F", 3, "M"],
  [164, "Akbar Putra Eko Wiyanto", "IX F", 4, "M"],
  [165, "Albian Pranaja Nugroho", "IX F", 5, "M"],
  [166, "Amira Natasya Ramadhani", "IX F", 6, "F"],
  [167, "Arrum Yulia Rahmawati", "IX F", 7, "F"],
  [168, "Aulia Asmaul Isna", "IX F", 8, "F"],
  [169, "Clarissa Dlovania", "IX F", 9, "F"],
  [170, "Daffandra Malika Nofrizal", "IX F", 10, "M"],
  [171, "Dimas Aldiansa", "IX F", 11, "M"],
  [172, "Hatta Maulana Anhar", "IX F", 12, "M"],
  [173, "Indi Safa Saputri", "IX F", 13, "F"],
  [174, "Januar Arga Pratama", "IX F", 14, "M"],
  [175, "Kayla Az Zahra Fajrani", "IX F", 15, "F"],
  [176, "Khoirul Zulfikar", "IX F", 16, "M"],
  [177, "Laila Nur Rahma", "IX F", 17, "F"],
  [178, "Latifa Berta Nurra Evitasari", "IX F", 18, "F"],
  [179, "Marvel Eka Cristian", "IX F", 19, "M"],
  [180, "Muhammad Gilang Saputra", "IX F", 20, "M"],
  [181, "Muhammad Rheihan Saputra", "IX F", 21, "M"],
  [182, "Myiesha Ayu Puspita", "IX F", 22, "F"],
  [183, "Nasya Nurul Hanifah", "IX F", 23, "F"],
  [184, "Nazril Ananda Nugroho", "IX F", 24, "M"],
  [185, "Novya Nur Kholifah", "IX F", 25, "F"],
  [186, "Oktavian Pulung Nugroho", "IX F", 26, "M"],
  [187, "Olivia Kumala Ningrum", "IX F", 27, "F"],
  [188, "Puguh Prasetyo Ardi", "IX F", 28, "M"],
  [189, "Safa Anugerahini", "IX F", 29, "F"],
  [190, "Safa Zahra Aisya Hakim", "IX F", 30, "F"],
  [191, "Taurizka Kusuma Wardani", "IX F", 31, "F"],
  [192, "Yoan Marsanto", "IX F", 32, "M"],
  // === IX G ===
  [193, "Anggit Dwi Nugroho", "IX G", 1, "M"],
  [194, "Anjani Gendhis Sunianto", "IX G", 2, "F"],
  [195, "Aurora Azizatul Muslimah", "IX G", 3, "F"],
  [196, "Avrilia Happy Nugrahany", "IX G", 4, "F"],
  [197, "Candra Edy Nugroho", "IX G", 5, "M"],
  [198, "Dimas Rizky Apriyadi", "IX G", 6, "M"],
  [199, "Eka Mutiara Putri Hidayah", "IX G", 7, "F"],
  [200, "Eka Prabandaru Mutiara Kasih", "IX G", 8, "F"],
  [201, "Farhan Dwi Khoirudin", "IX G", 9, "M"],
  [202, "Hafizal Zain Al Fairuz", "IX G", 10, "M"],
  [203, "Jasen Enzo Utomo", "IX G", 11, "M"],
  [204, "Kevin Aditia", "IX G", 12, "M"],
  [205, "Keysha Ardana Nareswari", "IX G", 13, "F"],
  [206, "Khansa Nur Rahmawati", "IX G", 14, "F"],
  [207, "Muhammad Dwi Arifin", "IX G", 15, "M"],
  [208, "Muhammad Khoirul Rizal", "IX G", 16, "M"],
  [209, "Najwa Sefie Melvia", "IX G", 17, "F"],
  [210, "Natasya Putri Nur Hidayanti", "IX G", 18, "F"],
  [211, "Nita Safitri", "IX G", 19, "F"],
  [212, "Noval Firmansyah", "IX G", 20, "M"],
  [213, "Noviana Wahyu Susilowati", "IX G", 21, "F"],
  [214, "Patta Mahesa Duta", "IX G", 22, "M"],
  [215, "Rafa Bagus Pramudya", "IX G", 23, "M"],
  [216, "Rafqi Maulana Afifuddin", "IX G", 24, "M"],
  [217, "Rahma Nur Aisha Febriyanti", "IX G", 25, "F"],
  [218, "Rangga Bagus Nur Cahyo", "IX G", 26, "M"],
  [219, "Rengganis Yuliyanti Maharani", "IX G", 27, "F"],
  [220, "Rifky Dean Pradipta", "IX G", 28, "M"],
  [221, "Shalma Rahma Amelia Qusnul Khazanah", "IX G", 29, "F"],
  [222, "Valen Naufal Alfaro", "IX G", 30, "M"],
  [223, "Widya Oktaviani Pangesti", "IX G", 31, "F"],
  [224, "Yasmin Putri Nurhidayah", "IX G", 32, "F"],
  // === IX H ===
  [225, "A'arifah Nuur Jannah", "IX H", 1, "F"],
  [226, "Adinda Putri Nur`Ani", "IX H", 2, "F"],
  [227, "Agil Nurchoiri Islamudin", "IX H", 3, "M"],
  [228, "Aisyah Sarifa Aiyni", "IX H", 4, "F"],
  [229, "Aldo Dhiva Pradistya", "IX H", 5, "M"],
  [230, "Ara Nadora Mardemy", "IX H", 6, "F"],
  [231, "Arka Adi Saputra", "IX H", 7, "M"],
  [232, "Arvian Vega Effendi", "IX H", 8, "M"],
  [233, "Bilqis Aqaila Zahrania", "IX H", 9, "F"],
  [234, "Cantika Putriana Nur Sabrina", "IX H", 10, "F"],
  [235, "Dianing Surya Amalia", "IX H", 11, "F"],
  [236, "Dina Sri Anggraini", "IX H", 12, "F"],
  [237, "Erlangga Putra Mustafa", "IX H", 13, "M"],
  [238, "Faizal Nur Aryanto", "IX H", 14, "M"],
  [239, "Fitria Tabitha Tristy", "IX H", 15, "F"],
  [240, "Gita Febrianti", "IX H", 16, "F"],
  [241, "Iffat Abbasy Azzuddin", "IX H", 17, "M"],
  [242, "Meisya Ajeng Pratiwi", "IX H", 18, "F"],
  [243, "Meisya Listyarini Putri", "IX H", 19, "F"],
  [244, "Muhammad Ibnu Darmawan", "IX H", 20, "M"],
  [245, "Muhammad Ilham", "IX H", 21, "M"],
  [246, "Nadine Putri Wulandari", "IX H", 22, "F"],
  [247, "Nafi'an Qolbi Nur'an", "IX H", 23, "M"],
  [248, "Nayla Ifa Nashiroh", "IX H", 24, "F"],
  [249, "Rangga Dwi Raditya", "IX H", 25, "M"],
  [250, "Rayqal Qarlif Ekma Putra", "IX H", 26, "M"],
  [251, "Rizki Faizal Novianto", "IX H", 27, "M"],
  [252, "Sya'dan Rifdo Sayoko", "IX H", 28, "M"],
  [253, "Syahwan Iswanto", "IX H", 29, "M"],
  [254, "Tegar Nasution", "IX H", 30, "M"],
  [255, "Vania Rahmawati", "IX H", 31, "F"],
  [256, "Zakiah Mariani", "IX H", 32, "F"],
];

// Build full student objects
const STUDENTS = RAW_STUDENTS.map(([no, name, cls, clsNo, gender]) => ({
  id: `${QR_PREFIX}-${String(no).padStart(3, '0')}`,
  qrCode: `${QR_PREFIX}-${String(no).padStart(3, '0')}`,
  overallNumber: no,
  name: name,
  class: cls,
  classNumber: clsNo,
  gender: gender,
  photo: null, // Will be loaded from localStorage
}));

// Lookup map by QR code
const STUDENT_MAP = {};
STUDENTS.forEach(s => { STUDENT_MAP[s.qrCode] = s; });

// Get student by QR code string
function getStudentByQR(qrValue) {
  const key = qrValue.trim().toUpperCase();
  return STUDENT_MAP[key] || null;
}

// Get student by overall number
function getStudentByNumber(num) {
  return STUDENTS.find(s => s.overallNumber === parseInt(num)) || null;
}

// Load photo from localStorage
function loadStudentPhoto(studentId) {
  return localStorage.getItem(`photo_${studentId}`) || null;
}

// Save photo to localStorage
function saveStudentPhoto(studentId, base64Data) {
  try {
    localStorage.setItem(`photo_${studentId}`, base64Data);
    return true;
  } catch (e) {
    console.warn('Storage full:', e);
    return false;
  }
}

// Remove photo
function removeStudentPhoto(studentId) {
  localStorage.removeItem(`photo_${studentId}`);
}
